name: muzn
description: "A new Flutter project for Quran Tahfeez."

publish_to: 'none' # Prevent accidental publication to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0 # Ensure compatibility with Flutter SDK
  provider: ^6.1.2
  intl_phone_field: ^3.2.0
  introduction_screen: ^3.1.14
  convex_bottom_bar: ^3.2.0
  google_fonts: ^6.2.1
  contextualactionbar: ^3.1.0
  input_quantity: ^2.5.1
  flutter_searchable_dropdown: ^2.0.0
  gif_view: ^1.0.0
  quran: ^1.3.3
  sqflite: ^2.2.0+4
  path: ^1.8.3
  shared_preferences: ^2.4.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.5   





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/ # Directory for translation files
    - assets/images/ # Directory for image 
    - assets/flags/ # Directory for image 
    - assets/static/muzn_database.db # Directory for database



